// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { Approval } from "./tables/Approval.sol";
import { Allowance } from "./tables/Allowance.sol";
import { Balance } from "./tables/Balance.sol";
import { TotalSupply } from "./tables/TotalSupply.sol";
import { StoredSize } from "./tables/StoredSize.sol";
import { Commander } from "./tables/Commander.sol";
import { Owner } from "./tables/Owner.sol";
import { EntityType } from "./tables/EntityType.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { TerrainEntity, TerrainEntityData } from "./tables/TerrainEntity.sol";
import { RemovedCoord } from "./tables/RemovedCoord.sol";
import { BuildingCoord } from "./tables/BuildingCoord.sol";
import { TerrainSpecs, TerrainSpecsData } from "./tables/TerrainSpecs.sol";
import { BuildingSpecs, BuildingSpecsData } from "./tables/BuildingSpecs.sol";
import { ERC20Specs, ERC20SpecsData } from "./tables/ERC20Specs.sol";
import { SizeSpecs } from "./tables/SizeSpecs.sol";
import { ContainerSpecs } from "./tables/ContainerSpecs.sol";
import { MintCosts } from "./tables/MintCosts.sol";
import { UpgradeCosts, UpgradeCostsData } from "./tables/UpgradeCosts.sol";
import { BurnCosts } from "./tables/BurnCosts.sol";
import { BurnAwards } from "./tables/BurnAwards.sol";
import { InteractCosts } from "./tables/InteractCosts.sol";
import { InteractAwards } from "./tables/InteractAwards.sol";
