// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { EntityType } from "./tables/EntityType.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { TerrainEntity, TerrainEntityData } from "./tables/TerrainEntity.sol";
import { RemovedCoord } from "./tables/RemovedCoord.sol";
import { BuildingCoord } from "./tables/BuildingCoord.sol";
import { TerrainSpecs, TerrainSpecsData } from "./tables/TerrainSpecs.sol";
import { BuildingSpecs, BuildingSpecsData } from "./tables/BuildingSpecs.sol";
