// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IErrors
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IErrors {
  error NotCommander();
  error NotApproved();
  error NotAdjacent();
  error CannotMoveToTerrain(bytes16 terrainType);
  error CannotMoveToBuilding(bytes32 coordId);
  error ExceedMaxMoves();
  error NotIncrementalMoves();
  error NotFromHostPosition();
  error InvalidMove();
  error MintToNull();
  error TransferFromNull();
  error TransferToNull();
  error TransferExceedsBalance();
  error TransferIncorrectOwner();
  error BurnFromNull();
  error BurnExceedsBalance();
  error Minted();
  error ApproveOwnerNull();
  error ApproveSpenderNull();
  error InsufficientAllowance();
  error InsufficientStorage();
  error StorageUnderflow();
  error NestedContainer();
  error HasBuildingOnCoord();
  error WrongTerrainToBuildOn();
  error NoBuildingOnCoord();
  error NoTerrainToBurn();
  error NoAvailableUpgrade();
}
